variable "env" {}
variable "tags" {}
variable "subnets" {}
variable "backup_retention_period" {}
variable "preferred_backup_window" {}
variable "skip_final_snapshot" {}
variable "vpc_id" {}
variable "cidr_blocks" {}
variable "instance_count" {}
variable "instance_class" {}
variable "engine_version" {}
variable "family" {}